name: Generate Fire Dragon Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate fire dragon snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=%23DC143C&color_dots=%23DC143C,%23FF4500,%23FF6347,%234B0082,%23800080
            dist/snake-dark.svg?palette=github-dark&color_snake=%23FF4500&color_dots=%23FF4500,%23DC143C,%23B22222,%23800080,%23000000
            dist/snake-light.svg?palette=github-light&color_snake=%234B0082&color_dots=%234B0082,%23DC143C,%23FF4500,%23FF6347,%23B22222

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}