name: Generate Medieval Kingdom Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate medieval snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=%23B8860B&color_dots=%23B8860B,%23DAA520,%23FFD700,%23CD853F,%238B4513
            dist/snake-dark.svg?palette=github-dark&color_snake=%23FFD700&color_dots=%23FFD700,%23DAA520,%23B8860B,%23CD853F,%23654321
            dist/snake-light.svg?palette=github-light&color_snake=%23B8860B&color_dots=%23B8860B,%23DAA520,%23FFD700,%23DEB887,%238B4513

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}