name: Generate Snake Game

on:
  schedule:
    # Runs at 12 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: AgnayS
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&color_snake=#00D4AA&color_dots=#00D4AA,#26a641,#39d353,#2E86AB,#FF6B35
            dist/snake-light.svg?palette=github-light&color_snake=#2E86AB&color_dots=#2E86AB,#39d353,#26a641,#00D4AA,#FF6B35

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}